import { CacheInterceptor } from '@nestjs/cache-manager';
import { ExecutionContext, Injectable } from '@nestjs/common';

@Injectable()
export class UserCacheInterceptor extends CacheInterceptor {
    trackBy(context: ExecutionContext): string | undefined {
        // Get the default cache key generated by the built-in interceptor
        const defaultKey = super.trackBy(context);
        const request = context.switchToHttp().getRequest();

        if (defaultKey && request?.user?.userId) {
            // Append the userId to the default cache key
            return `${defaultKey}:${request.user.userId}`;
        }
        return defaultKey;
    }
}
